# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18uxuECIrpt51nlmOop5NM0NjtUvKnJY9
"""

import matplotlib.pyplot as plt
import numpy as np

y=np.array([3,8,1,10])

plt.plot(y,marker='o')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

y=np.array([3,8,1,10])

plt.plot(y,'o:r')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

y=np.array([3,8,1,10])

plt.plot(y,marker='o',ms=20)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

y=np.array([3,8,1,10])

plt.plot(y,marker='o',ms=20, mec='r')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x1=np.array([0,1,2,3])
y1=np.array([3,8,1,10])
x2=np.array([0,1,2,3])
y2=np.array([6,2,7,11])

plt.plot(x1,y1,x2,y2)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

y=np.array([3,8,1,10])

plt.plot(y,marker='o',ms=20, mfc='r')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,1,2,3,4,5])
y=np.array([0,8,12,20,26,38])

plt.scatter(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,1,2,3,4,5])
y=np.array([0,2,8,1,14,7])
plt.scatter(x,y,color='red')

x==np.array([12,6,8,11,8,3])
y=np.array([5,6,3,7,17,19])

plt.scatter(x,y,color='green')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array(['22',"25",'18',"13"])
y=np.array([3,8,1,10])
plt.bar(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([35,25,25,15])


plt.pie(y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([35,25,25,15])
mylabels=['olma','banan','gilos','shaftoli']
plt.pie(y, labels=mylabels)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([35,25,25,15])
mylabels=['olma','banan','gilos','shaftoli']
myexplode=[0.2,0,0,0]
plt.pie(y, labels=mylabels, startangle=90, explode=myexplode)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([35,25,25,15])
mylabels=['olma','banan','gilos','shaftoli']
myexplode=[0.2,0,0,0]
plt.pie(y, labels=mylabels, startangle=90, explode=myexplode, shadow=True )
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([35,25,25,15])
mylabels=['olma','banan','gilos','shaftoli']
plt.pie(y, labels=mylabels)
plt.legend(title='Four Fruits')